modLoader = "javafml"
loaderVersion = "[47,)"
license = "LGPL-3.0-only"

[[mods]]
modId = "score_counter"
version = "${mod_version}"
displayName = "Score Counter"
authors = "Sindercube"
description = '''
Adds the Score counter from Indev to modern versions of Minecraft
'''
logoFile = "assets/score_counter/icon.png"

[[dependencies.score_counter]]
modId = "minecraft"
mandatory = false
versionRange = "(,1.0],[1.0,)"
side = "CLIENT"
